/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd202_finalproject_java;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student.admin
 */
public final class AdminPage extends javax.swing.JFrame {

    PreparedStatement pst = null;

    /**
     * Creates new form ad
     */
    public AdminPage() {
        initComponents();
        count();
        Approve();
        Admin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void showByFilter() {
        int col;
        String sportname = jFilter.getSelectedItem().toString();

        try {
            String myQuery = "SELECT * FROM `sports` WHERE sportName = ?";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement(myQuery);
            pst.setString(1, sportname);
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            col = rsd.getColumnCount();

            DefaultTableModel d = (DefaultTableModel) jTable4.getModel();
            d.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= col; i++) {
                    v2.add(rs.getString("sportsID"));
                    v2.add(rs.getString("sportName"));
                    v2.add(rs.getString("teamName"));
                    v2.add(rs.getString("scheduleDate"));
                    v2.add(rs.getString("timeStart"));
                    v2.add(rs.getString("duration_hrs"));
                    v2.add(rs.getString("timeEnd"));
                    v2.add(rs.getString("amount"));
                    v2.add(rs.getString("barcode"));
                    v2.add(rs.getString("status"));
                }
                d.addRow(v2);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dash = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        chartPanel = new javax.swing.JPanel();
        appro = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        teamname = new javax.swing.JTextField();
        scheduledate = new javax.swing.JTextField();
        sportname = new javax.swing.JTextField();
        Tend = new javax.swing.JTextField();
        Amount = new javax.swing.JTextField();
        Duration = new javax.swing.JTextField();
        update = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tstart = new javax.swing.JTextField();
        Barcode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox<>();
        Refresh = new javax.swing.JToggleButton();
        jFilter = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        addmin = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Add_Admin = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        role = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        idName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        jToggleButton8.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jToggleButton8.setText("Dashboard");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jToggleButton2.setText("Manage Sched");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jToggleButton3.setText("Add Admin");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jToggleButton4.setText("Logout");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 51));
        jLabel18.setText("Active: ");

        usertype.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        usertype.setForeground(new java.awt.Color(204, 255, 51));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("LoveSports");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usertype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));

        jPanel8.setBackground(new java.awt.Color(204, 255, 51));

        chartPanel.setBackground(new java.awt.Color(51, 51, 255));
        chartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashLayout = new javax.swing.GroupLayout(dash);
        dash.setLayout(dashLayout);
        dashLayout.setHorizontalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashLayout.setVerticalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", dash);

        jPanel9.setBackground(new java.awt.Color(204, 255, 51));
        jPanel9.setLayout(null);
        jPanel9.add(teamname);
        teamname.setBounds(55, 305, 121, 27);

        scheduledate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduledateActionPerformed(evt);
            }
        });
        jPanel9.add(scheduledate);
        scheduledate.setBounds(55, 364, 121, 28);

        sportname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportnameActionPerformed(evt);
            }
        });
        jPanel9.add(sportname);
        sportname.setBounds(233, 303, 121, 27);

        Tend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TendActionPerformed(evt);
            }
        });
        jPanel9.add(Tend);
        Tend.setBounds(55, 436, 121, 29);

        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });
        jPanel9.add(Amount);
        Amount.setBounds(233, 363, 121, 27);

        Duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationActionPerformed(evt);
            }
        });
        jPanel9.add(Duration);
        Duration.setBounds(442, 303, 119, 28);

        update.setBackground(new java.awt.Color(255, 153, 0));
        update.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel9.add(update);
        update.setBounds(358, 498, 78, 29);

        jToggleButton7.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jToggleButton7.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton7.setText("Delete");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jToggleButton7);
        jToggleButton7.setBounds(233, 496, 88, 29);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "SportName", "TeamName", "ScheduleDate", "TimeStart", "duration_hrs", "TimeEnd", "amount", "barcode", "Status"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(-4, 1, 620, 220);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("SportName: ");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(233, 277, 58, 20);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TeamName: ");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(55, 279, 58, 20);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Amount:");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(233, 337, 40, 20);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ScheduleDate: ");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(55, 338, 69, 20);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("TimeEnd:");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(55, 410, 45, 20);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Duration");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(442, 277, 40, 20);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("ID:");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(55, 471, 13, 20);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel9.add(ID);
        ID.setBounds(55, 497, 121, 28);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Time Start: ");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(233, 408, 55, 20);

        Tstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TstartActionPerformed(evt);
            }
        });
        jPanel9.add(Tstart);
        Tstart.setBounds(233, 434, 121, 28);

        Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarcodeActionPerformed(evt);
            }
        });
        jPanel9.add(Barcode);
        Barcode.setBounds(442, 364, 119, 28);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Barcode:");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(442, 338, 41, 20);

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Status:");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(442, 404, 32, 20);

        Status.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approve", "" }));
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel9.add(Status);
        Status.setBounds(442, 430, 119, 32);

        Refresh.setBackground(new java.awt.Color(51, 255, 51));
        Refresh.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel9.add(Refresh);
        Refresh.setBounds(478, 496, 83, 34);

        jFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basketball", "Volleyball", "Badminton" }));
        jPanel9.add(jFilter);
        jFilter.setBounds(210, 230, 111, 31);

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);
        jButton4.setBounds(330, 230, 72, 31);

        javax.swing.GroupLayout approLayout = new javax.swing.GroupLayout(appro);
        appro.setLayout(approLayout);
        approLayout.setHorizontalGroup(
            approLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        approLayout.setVerticalGroup(
            approLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", appro);

        jPanel11.setBackground(new java.awt.Color(204, 255, 51));
        jPanel11.setForeground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "fullName", "email", "address", "username", "password", "role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel11.add(jScrollPane3);
        jScrollPane3.setBounds(-3, 5, 620, 230);

        Add_Admin.setBackground(new java.awt.Color(0, 102, 255));
        Add_Admin.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        Add_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Add_Admin.setText("Add Admin");
        Add_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_AdminActionPerformed(evt);
            }
        });
        jPanel11.add(Add_Admin);
        Add_Admin.setBounds(330, 480, 100, 38);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("address:");
        jPanel11.add(jLabel11);
        jLabel11.setBounds(80, 390, 46, 20);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("fullname:");
        jPanel11.add(jLabel9);
        jLabel9.setBounds(80, 260, 49, 20);

        fullname.setForeground(new java.awt.Color(51, 51, 51));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel11.add(fullname);
        fullname.setBounds(80, 280, 140, 26);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("email:");
        jPanel11.add(jLabel10);
        jLabel10.setBounds(80, 320, 31, 20);

        email.setForeground(new java.awt.Color(51, 51, 51));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel11.add(email);
        email.setBounds(80, 350, 140, 31);

        address.setForeground(new java.awt.Color(51, 51, 51));
        jPanel11.add(address);
        address.setBounds(80, 420, 140, 32);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("username: ");
        jPanel11.add(jLabel12);
        jLabel12.setBounds(300, 320, 58, 20);

        role.setForeground(new java.awt.Color(51, 51, 51));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel11.add(role);
        role.setBounds(300, 420, 130, 32);

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("role:");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(300, 400, 24, 20);

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("password:");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(300, 260, 56, 20);

        username.setForeground(new java.awt.Color(51, 51, 51));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel11.add(username);
        username.setBounds(300, 350, 130, 31);

        pass.setForeground(new java.awt.Color(51, 51, 51));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel11.add(pass);
        pass.setBounds(300, 280, 130, 26);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1);
        jButton1.setBounds(460, 320, 82, 26);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2);
        jButton2.setBounds(460, 410, 82, 26);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3);
        jButton3.setBounds(460, 360, 82, 26);

        idName.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        idName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNameActionPerformed(evt);
            }
        });
        jPanel11.add(idName);
        idName.setBounds(80, 480, 140, 32);

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("ID:");
        jPanel11.add(jLabel17);
        jLabel17.setBounds(80, 460, 15, 20);

        javax.swing.GroupLayout addminLayout = new javax.swing.GroupLayout(addmin);
        addmin.setLayout(addminLayout);
        addminLayout.setHorizontalGroup(
            addminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addminLayout.setVerticalGroup(
            addminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", addmin);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, 610, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        count();

    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        Approve();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Wanna logout??", "CONFIRMATION!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LandingPage().setVisible(true);
            this.dispose();
        } else {
            // no option
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (usertype.getText().equals("Existing Admin")) {
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            int Selected = jTable3.getSelectedRow();
            try {
                int id = Integer.parseInt(model.getValueAt(Selected, 0).toString());
                int delete = JOptionPane.showConfirmDialog(null, "Confirm to Delete", "Warning", JOptionPane.YES_NO_OPTION);
                if (delete == JOptionPane.YES_OPTION) {
                    String sql = "DELETE FROM `users` WHERE `userID` = ?";

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");

                    pst = conn.prepareStatement(sql);
                    pst.setInt(1, id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "User delete successfully");

                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, only \"Existing Admin\" can delete!", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        Admin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Admin();
        fullname.setText(null);
        role.setText(null);
        email.setText(null);
        address.setText(null);
        username.setText(null);
        pass.setText(null);
        idName.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (usertype.getText().equals("Existing Admin")) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");

                String fName = fullname.getText();
                String emaill = email.getText();
                String addr = address.getText();
                String userN = username.getText();
                String passwo = pass.getText();

                String sql = "UPDATE `users` SET `fullName`='" + fName + "',`email`='" + emaill + "',`address`='" + addr + "',`username`='" + userN + "',`password`='" + passwo + "'WHERE `userID`='" + idName.getText() + "'";

                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated");
                //            Approve();
            } catch (Exception e) {
                e.getMessage();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Sorry, only \"Existing Admin\" can update!", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        Admin();
        fullname.setText(null);
        role.setText(null);
        email.setText(null);
        address.setText(null);
        username.setText(null);
        pass.setText(null);
        idName.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void Add_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_AdminActionPerformed
        // TODO add your handling code here:
        if (usertype.getText().equals("Existing Admin")) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");
                //here sonoo is database name, root is username and password

                String sql = "INSERT INTO `users`( `fullName`, `email`, `address`, `username`, `password`, `role`) VALUES (?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, fullname.getText());
                pst.setString(2, email.getText());
                pst.setString(3, address.getText());
                pst.setString(4, username.getText());
                pst.setString(5, pass.getText());
                pst.setString(6, role.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Admin Added");

            } catch (Exception e) {
                e.getMessage();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, only \"Existing Admin\" can add!", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        Admin();
        fullname.setText(null);
        role.setText(null);
        email.setText(null);
        address.setText(null);
        username.setText(null);
        pass.setText(null);
        idName.setText(null);

    }//GEN-LAST:event_Add_AdminActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        String id = model.getValueAt(jTable3.getSelectedRow(), 0).toString();
        String support = model.getValueAt(jTable3.getSelectedRow(), 1).toString();
        String team = model.getValueAt(jTable3.getSelectedRow(), 2).toString();
        String schedule = model.getValueAt(jTable3.getSelectedRow(), 3).toString();
        String start = model.getValueAt(jTable3.getSelectedRow(), 4).toString();
        String duration = model.getValueAt(jTable3.getSelectedRow(), 5).toString();
        String end = model.getValueAt(jTable3.getSelectedRow(), 6).toString();

        idName.setText(id);
        fullname.setText(support);
        email.setText(team);
        address.setText(schedule);
        username.setText(start);
        pass.setText(duration);
        role.setText(end);
    }//GEN-LAST:event_jTable3MouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        Approve();
    }//GEN-LAST:event_RefreshActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarcodeActionPerformed

    private void TstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TstartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TstartActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        String id = model.getValueAt(jTable4.getSelectedRow(), 0).toString();
        String support = model.getValueAt(jTable4.getSelectedRow(), 1).toString();
        String team = model.getValueAt(jTable4.getSelectedRow(), 2).toString();
        String schedule = model.getValueAt(jTable4.getSelectedRow(), 3).toString();
        String start = model.getValueAt(jTable4.getSelectedRow(), 4).toString();
        String duration = model.getValueAt(jTable4.getSelectedRow(), 5).toString();
        String end = model.getValueAt(jTable4.getSelectedRow(), 6).toString();
        String amount = model.getValueAt(jTable4.getSelectedRow(), 7).toString();
        String barcode = model.getValueAt(jTable4.getSelectedRow(), 8).toString();
        String status = model.getValueAt(jTable4.getSelectedRow(), 9).toString();

        ID.setText(id);
        sportname.setText(support);
        teamname.setText(team);
        scheduledate.setText(schedule);
        Duration.setText(duration);
        Tend.setText(end);
        Amount.setText(amount);
        Tstart.setText(start);
        Barcode.setText(barcode);
        Status.setSelectedItem(status);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int Selected = jTable4.getSelectedRow();
        try {
            int id = Integer.parseInt(model.getValueAt(Selected, 0).toString());
            int delete = JOptionPane.showConfirmDialog(null, "Confirm to Delete", "Warning", JOptionPane.YES_NO_OPTION);
            if (delete == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM `sports` WHERE `sportsID` = ?";

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");

                pst = conn.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Schedule delete successfully");

                ID.setText("");
                sportname.setText("");
                teamname.setText("");
                scheduledate.setText("");
                Duration.setText("");
                Tend.setText("");
                Amount.setText("");
                Tstart.setText("");
                Status.setSelectedIndex(0);
                Barcode.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);

        }

        Admin();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");

            String id = ID.getText();
            String sport = sportname.getText();
            String team = teamname.getText();
            String date = scheduledate.getText();
            String start = Tstart.getText();
            String duration = Duration.getText();
            String end = Tend.getText();
            String amount = Amount.getText();
            String barcode = Barcode.getText();
            String status = Status.getSelectedItem().toString();

            String sql = "UPDATE `sports` SET `sportName`='" + sport + "',`teamName`='" + team + "',`scheduleDate`='" + date + "',`timeStart`='" + start + "',`duration_hrs`='" + duration + "',`timeEnd`='" + end + "',`amount`='" + amount + "', `barcode`='" + barcode + "', `status`='" + status + "' WHERE `sportsID`='" + id + "'";

            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
            //            Approve();
        } catch (Exception e) {
            e.getMessage();
        }
        Approve();
    }//GEN-LAST:event_updateActionPerformed

    private void DurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void TendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TendActionPerformed

    private void sportnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportnameActionPerformed

    private void scheduledateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduledateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduledateActionPerformed

    private void idNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showByFilter();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void count() {
        try {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            dataset.setValue(count.countData("sports"), "Total", "Pending Schedules");
            dataset.setValue(count.countdata("sports"), "Total", "Approve Schedules");
            dataset.setValue(count.admin("users"), "Total", "Users");

            JFreeChart chart = ChartFactory.createBarChart("Statistics", "Schedules Status & Users", "Total", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = chart.getCategoryPlot();
            p.setRangeGridlinePaint(Color.BLACK);

            ChartPanel CP = new ChartPanel(chart);
            chartPanel.removeAll();
            chartPanel.add(CP, BorderLayout.CENTER);
            chartPanel.validate();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void Approve() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");
            Statement st;

            st = conn.createStatement();
            ResultSet rs;

            rs = st.executeQuery("SELECT * FROM `sports`");
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getInt("sportsID"), rs.getString("sportName"), rs.getString("teamName"), rs.getDate("scheduleDate"), rs.getString("timeStart"), rs.getString("duration_hrs"), rs.getString("timeEnd"), rs.getString("amount"), rs.getString("barcode"), rs.getString("status")};
                model.addRow(o);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void Admin() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sport_scheduler", "root", "");

            Statement st;

            st = conn.createStatement();
            ResultSet rs;

            rs = st.executeQuery("SELECT * FROM `users` ");
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("userID"), rs.getString("fullName"), rs.getString("email"), rs.getString("address"), rs.getString("username"), rs.getString("password"), rs.getString("role")};
                model.addRow(o);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Add_Admin;
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Barcode;
    private javax.swing.JTextField Duration;
    private javax.swing.JTextField ID;
    private javax.swing.JToggleButton Refresh;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField Tend;
    private javax.swing.JTextField Tstart;
    private javax.swing.JPanel addmin;
    private javax.swing.JTextField address;
    private javax.swing.JPanel appro;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JPanel dash;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField idName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField role;
    private javax.swing.JTextField scheduledate;
    private javax.swing.JTextField sportname;
    private javax.swing.JTextField teamname;
    private javax.swing.JToggleButton update;
    private javax.swing.JTextField username;
    public javax.swing.JLabel usertype;
    // End of variables declaration//GEN-END:variables
}
