/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd202_finalproject_java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student.Admin
 */
public class CreateSchedule extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form CreateSchedule
     */
    public CreateSchedule() {
        initComponents();
        showSched();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void showSched() {
        int col;
        try {
            String myQuery = "SELECT * FROM sports";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement(myQuery);
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            col = rsd.getColumnCount();

            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= col; i++) {
                    v2.add(rs.getString("sportName"));
                    v2.add(rs.getString("teamName"));
                    v2.add(rs.getString("scheduleDate"));
                    v2.add(rs.getString("timeStart"));
                    v2.add(rs.getString("duration_hrs"));
                    v2.add(rs.getString("timeEnd"));
                    v2.add(rs.getString("status"));
                }
                d.addRow(v2);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void showByFilter() {
        int col;
        String sportname = jFilter.getSelectedItem().toString();

        try {
            String myQuery = "SELECT * FROM `sports` WHERE sportName = ?";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement(myQuery);
            pst.setString(1, sportname);
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            col = rsd.getColumnCount();

            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= col; i++) {
                    v2.add(rs.getString("sportName"));
                    v2.add(rs.getString("teamName"));
                    v2.add(rs.getString("scheduleDate"));
                    v2.add(rs.getString("timeStart"));
                    v2.add(rs.getString("duration_hrs"));
                    v2.add(rs.getString("timeEnd"));
                    v2.add(rs.getString("status"));
                }
                d.addRow(v2);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void checkExisting() {
        // date now
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime timeNow = LocalDateTime.now();
        String date = dtf.format(timeNow);

        //set date manually for schedule
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String sn = sportsName.getSelectedItem().toString();
        String tn = teamsName.getText();
        String sd = sdf.format(jDateChooser1.getDate());
        String ts = timeStart.getText()+ " " +jComboBox2.getSelectedItem();
        String dur = (jComboBox1.getText());
        String te = timeEnd.getText() + " " + jComboBox3.getSelectedItem();
        String amo = (jBarcode.getText());
        String bc = (jBarcode.getText());
        String stat = "Pending";

        try {
            String myQuery = "SELECT * FROM sports WHERE scheduleDate=? AND timeStart=? AND timeEnd=?";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement(myQuery);
            pst.setString(1, sdf.format(jDateChooser1.getDate()));
            pst.setString(2, timeStart.getText() + " " + jComboBox2.getSelectedItem());
            pst.setString(3, timeEnd.getText() + " " + jComboBox3.getSelectedItem());

            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Oops, it is already exists!", "Checking-Time!", JOptionPane.ERROR_MESSAGE);
            } else {
                if (sn.isEmpty() || tn.isEmpty() || sd.isEmpty() || ts.isEmpty() || dur.isEmpty() || ts.isEmpty() || amo.isEmpty() || bc.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Oops! input something!", "Error!", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String myQuery2 = "insert into sports (sportName, teamName,scheduleDate, timeStart, duration_hrs, timeEnd, amount, barcode, status, dateNow)values(?,?,?,?,?,?,?,?,?,?)";
                        pst = con.prepareStatement(myQuery2);
                        pst.setString(1, sn);
                        pst.setString(2, tn);
                        pst.setString(3, sd);
                        pst.setString(4, ts);
                        pst.setString(5, dur);
                        pst.setString(6, te);
                        pst.setString(7, amo);
                        pst.setString(8, bc);
                        pst.setString(9, stat);
                        pst.setString(10, date);

                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Successfuly Added.\nWait for Admins approval.", "Goods!", JOptionPane.INFORMATION_MESSAGE);

                        sportsName.setSelectedItem(null);
                        teamsName.setText(null);
                        jDateChooser1.setDate(null);
                        timeStart.setText(null);
                        jBarcode.setText(null);
                        jComboBox1.setText(null);
                        timeEnd.setText(null);
                        jAmount.setText(null);

                    } catch (SQLException ex) {
                        Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jFilter = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSubmit = new javax.swing.JButton();
        timeStart = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBarcode = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        timeEnd = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        teamsName = new javax.swing.JTextField();
        jSubmit1 = new javax.swing.JButton();
        jAmount = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        sportsName = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Schedule");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(712, 500));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        jTable1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SportName", "TeamsName", "Schedule", "TimeStart", "duration(hrs)", "TimeEnd", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LoveSports");

        jLabel29.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Home");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("About");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Schedules");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Login");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCode.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jCode.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        jCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodeActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basketball", "Volleyball", "Badminton" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(308, 308, 308))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Display Schedules", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 102, 0));
        jPanel4.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Gabriola", 1, 55)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ATHLETES.");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(100, 250, 220, 100);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LoveSports");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 20, 130, 30);

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("About");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21);
        jLabel21.setBounds(470, 30, 50, 20);

        jLabel22.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Schedules");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel22);
        jLabel22.setBounds(530, 30, 70, 20);

        jLabel23.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Login");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23);
        jLabel23.setBounds(620, 30, 50, 20);

        jLabel24.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Lovesports");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(170, 110, 100, 21);

        jLabel25.setFont(new java.awt.Font("Gabriola", 1, 25)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Welcome to Lovesports.");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(110, 140, 200, 60);

        jLabel26.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("designed just for you");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(130, 210, 160, 60);

        jLabel27.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("A system");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(170, 180, 80, 60);

        jPanel5.setBackground(new java.awt.Color(226, 115, 4));
        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Schedule Here");
        jLabel9.setAlignmentY(5);
        jPanel5.add(jLabel9);
        jLabel9.setBounds(90, 20, 120, 24);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sports Name:");
        jLabel8.setAlignmentY(5);
        jPanel5.add(jLabel8);
        jLabel8.setBounds(30, 60, 84, 25);

        jSubmit.setBackground(new java.awt.Color(0, 51, 204));
        jSubmit.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });
        jPanel5.add(jSubmit);
        jSubmit.setBounds(140, 310, 120, 31);

        timeStart.setBackground(new java.awt.Color(226, 115, 4));
        timeStart.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        timeStart.setForeground(new java.awt.Color(255, 255, 255));
        timeStart.setAlignmentY(5);
        timeStart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        timeStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeStartMouseClicked(evt);
            }
        });
        timeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartActionPerformed(evt);
            }
        });
        jPanel5.add(timeStart);
        timeStart.setBounds(140, 150, 43, 20);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Schedule Date:");
        jLabel11.setAlignmentY(5);
        jPanel5.add(jLabel11);
        jLabel11.setBounds(30, 120, 100, 25);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Teams Name:");
        jLabel13.setAlignmentY(5);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(30, 90, 84, 25);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Time Start:");
        jLabel10.setAlignmentY(5);
        jPanel5.add(jLabel10);
        jLabel10.setBounds(30, 150, 68, 25);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duration (hr):");
        jLabel12.setAlignmentY(5);
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 180, 90, 25);

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amount:");
        jLabel14.setAlignmentY(5);
        jPanel5.add(jLabel14);
        jLabel14.setBounds(30, 240, 53, 19);

        jBarcode.setBackground(new java.awt.Color(226, 115, 4));
        jBarcode.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jBarcode.setForeground(new java.awt.Color(255, 255, 255));
        jBarcode.setAlignmentY(5);
        jBarcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jBarcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBarcodeMouseClicked(evt);
            }
        });
        jBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarcodeActionPerformed(evt);
            }
        });
        jPanel5.add(jBarcode);
        jBarcode.setBounds(140, 270, 120, 20);

        jComboBox1.setBackground(new java.awt.Color(226, 115, 4));
        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(140, 180, 120, 20);

        jComboBox2.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(190, 150, 70, 25);

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Time End:");
        jLabel15.setAlignmentY(5);
        jPanel5.add(jLabel15);
        jLabel15.setBounds(30, 210, 68, 25);

        timeEnd.setBackground(new java.awt.Color(226, 115, 4));
        timeEnd.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        timeEnd.setForeground(new java.awt.Color(255, 255, 255));
        timeEnd.setAlignmentY(5);
        timeEnd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        timeEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeEndMouseClicked(evt);
            }
        });
        timeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeEndActionPerformed(evt);
            }
        });
        jPanel5.add(timeEnd);
        timeEnd.setBounds(140, 210, 43, 20);

        jComboBox3.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(190, 210, 70, 25);

        teamsName.setBackground(new java.awt.Color(226, 115, 4));
        teamsName.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        teamsName.setForeground(new java.awt.Color(255, 255, 255));
        teamsName.setAlignmentY(5);
        teamsName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        teamsName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamsNameMouseClicked(evt);
            }
        });
        teamsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamsNameActionPerformed(evt);
            }
        });
        jPanel5.add(teamsName);
        teamsName.setBounds(140, 90, 120, 20);

        jSubmit1.setBackground(new java.awt.Color(204, 102, 0));
        jSubmit1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jSubmit1.setForeground(new java.awt.Color(255, 255, 255));
        jSubmit1.setText("Barcode");
        jSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmit1ActionPerformed(evt);
            }
        });
        jPanel5.add(jSubmit1);
        jSubmit1.setBounds(30, 270, 90, 26);

        jAmount.setBackground(new java.awt.Color(226, 115, 4));
        jAmount.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jAmount.setForeground(new java.awt.Color(255, 255, 255));
        jAmount.setAlignmentY(5);
        jAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAmountMouseClicked(evt);
            }
        });
        jAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountActionPerformed(evt);
            }
        });
        jPanel5.add(jAmount);
        jAmount.setBounds(140, 240, 120, 20);
        jPanel5.add(jDateChooser1);
        jDateChooser1.setBounds(140, 110, 120, 30);

        sportsName.setBackground(new java.awt.Color(226, 115, 4));
        sportsName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sportsName.setForeground(new java.awt.Color(255, 255, 255));
        sportsName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basketball", "Volleyball", "Badminton" }));
        jPanel5.add(sportsName);
        sportsName.setBounds(140, 60, 120, 26);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(360, 80, 290, 350);

        jLabel28.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Home");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel28);
        jLabel28.setBounds(400, 30, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Image\\shedSet.png")); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(60, 80, 300, 350);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Schedule", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:

        if (jComboBox1.getText().isEmpty()) {
            timeEnd.setText(null);
            jAmount.setText(null);
        } else {
            String jBox1 = (String) jComboBox2.getSelectedItem();
            String jBox2 = (String) jComboBox3.getSelectedItem();
            int fixprice_perHour = 350;
            int tmstrt = Integer.parseInt(timeStart.getText());
            int hr = Integer.parseInt(jComboBox1.getText());
            int payable = fixprice_perHour * hr;
            int totalHour = hr + tmstrt;

            if (totalHour == 12 && "AM".equals(jBox1)) {
                jAmount.setText(Integer.toString(payable));
                timeEnd.setText(Integer.toString(totalHour));
                jComboBox3.setSelectedIndex(1);
            } else if (totalHour == 12 && "PM".equals(jBox1)) {
                jAmount.setText(Integer.toString(payable));
                timeEnd.setText(Integer.toString(totalHour));
                jComboBox3.setSelectedIndex(0);
            } else if (totalHour <= 12 && "AM".equals(jBox1)) {
                jAmount.setText(Integer.toString(payable));
                timeEnd.setText(Integer.toString(totalHour));
                jComboBox3.setSelectedItem(jComboBox2.getSelectedItem().toString());
            } else if (totalHour <= 12 && "PM".equals(jBox1)) {
                jAmount.setText(Integer.toString(payable));
                timeEnd.setText(Integer.toString(totalHour));
                jComboBox3.setSelectedItem(jComboBox2.getSelectedItem().toString());
            } else if (totalHour >= 12 && "AM".equals(jBox1)) {
                int res = totalHour - 12;
                jAmount.setText(Integer.toString(payable));
                timeEnd.setText(Integer.toString(res));
                jComboBox3.setSelectedIndex(1);
            } else if (totalHour > 12 && "PM".equals(jBox1)) {
                jAmount.setText(Integer.toString(payable));
                int res = totalHour - 12;
                timeEnd.setText(Integer.toString(res));
                jComboBox3.setSelectedIndex(0);
            }
        }

    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBarcodeActionPerformed

    private void jBarcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBarcodeMouseClicked
        // TODO add your handling code here:
        jBarcode.setEditable(false);
    }//GEN-LAST:event_jBarcodeMouseClicked

    private void timeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeStartActionPerformed

    private void timeStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeStartMouseClicked
        // TODO add your handling code here:
        timeStart.setText(null);
    }//GEN-LAST:event_timeStartMouseClicked

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        checkExisting();
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        new CreateSchedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        About a = new About();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showSched();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        new CreateSchedule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void timeEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeEndMouseClicked
        // TODO add your handling code here:
        timeEnd.setEditable(false);
    }//GEN-LAST:event_timeEndMouseClicked

    private void timeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeEndActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here:
        jComboBox3.setEditable(false);
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void teamsNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamsNameMouseClicked
        // TODO add your handling code here:
        teamsName.setText(null);
    }//GEN-LAST:event_teamsNameMouseClicked

    private void teamsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamsNameActionPerformed

    private void scheduleDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scheduleDateKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_scheduleDateKeyReleased

    private void jSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmit1ActionPerformed
        // TODO add your handling code here:
        java.util.Random r = new java.util.Random();
        int start = 100;
        int end = 1000;
        int result = r.nextInt(end - start) + start;
        jBarcode.setText(String.valueOf(result));
    }//GEN-LAST:event_jSubmit1ActionPerformed

    private void jAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAmountMouseClicked
        // TODO add your handling code here:
        jAmount.setEditable(false);
    }//GEN-LAST:event_jAmountMouseClicked

    private void jAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAmountActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        try {
            String barcode = jCode.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement("select * from sports where barcode=?");

            pst.setString(1, barcode);
            rs = pst.executeQuery();

            if (barcode.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill the required field!", "Input Something!", JOptionPane.ERROR_MESSAGE);

            } else if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Barcode doesn't Exist!", "Input Correctly!", JOptionPane.ERROR_MESSAGE);
                jCode.setText("");
            } else {
                String stat = rs.getString("status");

                JOptionPane.showMessageDialog(null, "Your schedule status is: " + stat.toUpperCase(), "Status!", JOptionPane.PLAIN_MESSAGE);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        showByFilter();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAmount;
    private javax.swing.JTextField jBarcode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCode;
    private javax.swing.JTextField jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JComboBox<String> jFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmit;
    private javax.swing.JButton jSubmit1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sportsName;
    private javax.swing.JTextField teamsName;
    private javax.swing.JTextField timeEnd;
    private javax.swing.JTextField timeStart;
    // End of variables declaration//GEN-END:variables
}
