/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd202_finalproject_java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student.Admin
 */
public class CreateSchedule extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form CreateSchedule
     */
    public CreateSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void showSched() {
        int col;
        try {
            String myQuery = "SELECT * FROM sports";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
            pst = con.prepareStatement(myQuery);
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            col = rsd.getColumnCount();

            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= col; i++) {
                    v2.add(rs.getString("sportsName"));
                    v2.add(rs.getString("teamsName"));
                    v2.add(rs.getString("scheduleDate"));
                    v2.add(rs.getString("timeStart"));
                    v2.add(rs.getString("timeEnd"));
                    v2.add(rs.getString("status"));
                }
                d.addRow(v2);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sportsName = new javax.swing.JTextField();
        teamsName = new javax.swing.JTextField();
        timeStart = new javax.swing.JTextField();
        scheduleDate = new javax.swing.JTextField();
        timeEnd = new javax.swing.JTextField();
        jSubmit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Schedule");

        jPanel4.setBackground(new java.awt.Color(179, 147, 39));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel8.setText("Sports Name:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(394, 117, 84, 19);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel9.setText("Schedule Here");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(453, 60, 113, 24);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel10.setText("Time Start:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(394, 246, 68, 19);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel11.setText("Schedule Date:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(394, 203, 93, 19);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel12.setText("Time End:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(394, 289, 64, 19);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel13.setText("Teams Name:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(394, 160, 84, 19);

        sportsName.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        sportsName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sportsNameMouseClicked(evt);
            }
        });
        sportsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsNameActionPerformed(evt);
            }
        });
        jPanel4.add(sportsName);
        sportsName.setBounds(507, 114, 114, 25);

        teamsName.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        teamsName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamsNameMouseClicked(evt);
            }
        });
        teamsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamsNameActionPerformed(evt);
            }
        });
        jPanel4.add(teamsName);
        teamsName.setBounds(507, 157, 114, 25);

        timeStart.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        timeStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeStartMouseClicked(evt);
            }
        });
        timeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartActionPerformed(evt);
            }
        });
        jPanel4.add(timeStart);
        timeStart.setBounds(507, 243, 114, 25);

        scheduleDate.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        scheduleDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleDateMouseClicked(evt);
            }
        });
        scheduleDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleDateActionPerformed(evt);
            }
        });
        jPanel4.add(scheduleDate);
        scheduleDate.setBounds(507, 200, 114, 25);

        timeEnd.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        timeEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeEndMouseClicked(evt);
            }
        });
        timeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeEndActionPerformed(evt);
            }
        });
        jPanel4.add(timeEnd);
        timeEnd.setBounds(507, 286, 114, 25);

        jSubmit.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });
        jPanel4.add(jSubmit);
        jSubmit.setBounds(523, 329, 79, 31);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("LOGO HERE!");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 0, 90, 41);

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel15.setText("Lovesports");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(140, 70, 100, 24);

        jLabel16.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        jLabel16.setText("Welcome to Lovesports");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(70, 130, 230, 60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Schedule", jPanel3);

        jPanel2.setBackground(new java.awt.Color(179, 147, 39));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SportName", "TeamsName", "Schedule", "TimeStart", "TimeEnd", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(303, 303, 303))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Display Schedules", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sportsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsNameActionPerformed

    private void teamsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamsNameActionPerformed

    private void timeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeStartActionPerformed

    private void scheduleDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleDateActionPerformed

    private void timeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeEndActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime timeNow = LocalDateTime.now();
        String date = dtf.format(timeNow);

        String sn = sportsName.getText();
        String tn = teamsName.getText();
        String sd = scheduleDate.getText();
        String ts = timeStart.getText();
        String te = timeEnd.getText();
        String stat = "pending";

        if ((!"".equals(sn)) && (!"".equals(tn)) && (!"".equals(sd)) && (!"".equals(ts)) && (!"".equals(te))) {
            try {
                String myQuery = "insert into sports (date, sportsName, teamsName,scheduleDate, timeStart, timeEnd, status)values(?,?,?,?,?,?,?)";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/sport_scheduler", "root", "");
                pst = con.prepareStatement(myQuery);
                pst.setString(1, date);
                pst.setString(2, sn);
                pst.setString(3, tn);
                pst.setString(4, sd);
                pst.setString(5, ts);
                pst.setString(6, te);
                pst.setString(7, stat);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfuly Added.\nWait for Admins approval.", "Goods!", JOptionPane.INFORMATION_MESSAGE);

                sportsName.setText(null);
                teamsName.setText(null);
                scheduleDate.setText(null);
                timeStart.setText(null);
                timeEnd.setText(null);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CreateSchedule.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops! input something!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showSched();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sportsNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sportsNameMouseClicked
        // TODO add your handling code here:
        sportsName.setText(null);
        
    }//GEN-LAST:event_sportsNameMouseClicked

    private void teamsNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamsNameMouseClicked
        // TODO add your handling code here:
        teamsName.setText(null);
    }//GEN-LAST:event_teamsNameMouseClicked

    private void scheduleDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleDateMouseClicked
        // TODO add your handling code here:
        scheduleDate.setText(null);
    }//GEN-LAST:event_scheduleDateMouseClicked

    private void timeStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeStartMouseClicked
        // TODO add your handling code here:
        timeStart.setText(null);
    }//GEN-LAST:event_timeStartMouseClicked

    private void timeEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeEndMouseClicked
        // TODO add your handling code here:
        timeEnd.setText(null);
    }//GEN-LAST:event_timeEndMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField scheduleDate;
    private javax.swing.JTextField sportsName;
    private javax.swing.JTextField teamsName;
    private javax.swing.JTextField timeEnd;
    private javax.swing.JTextField timeStart;
    // End of variables declaration//GEN-END:variables
}
